# Настройки Ghostty для nuc
font-family = JetBrains Mono
font-size = 12
background = #000000
foreground = #e6e6e6
background-opacity = 1
window-theme = dark
window-padding-x = 10
window-padding-y = 8
cursor-style = block
cursor-style-blink = false
mouse-hide-while-typing = true
scrollback-limit = 33554432
confirm-close-surface = true
# Размер окна
window-width = 240
window-height = 80